# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://theanonymous.github.io
title: Uploader
email: battleman2004 AT gmail.com
description: Uploader a simple HTTP Server with Up and Download function. Also other personal blog posts.

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "with_toc_data", "fenced_code_blocks"]

permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/wildanonymous
  - title: github
    url: https://github.com/TheAnonymous
  - title: google-plus
    url: https://plus.google.com/+JakobOesterling/about
